In [1]:
A1=[0 1
-9 -6]

2×2 Matrix{Int64}:
  0   1
 -9  -6

In [2]:
using SymPy

In [3]:
@vars t

(t,)

In [4]:
eat1=exp(A1*t)

┌ Warning: `vendor()` is deprecated, use `BLAS.get_config()` and inspect the output instead
│   caller = npyinitialize() at numpy.jl:67
└ @ PyCall /home/ec2-user/.julia/packages/PyCall/L0fLP/src/numpy.jl:67


2×2 Matrix{Sym}:
 3*t*exp(-3*t) + exp(-3*t)                 t*exp(-3*t)
            -9*t*exp(-3*t)  -3*t*exp(-3*t) + exp(-3*t)

In [5]:
M1=[6 9
9 0]

2×2 Matrix{Int64}:
 6  9
 9  0

In [6]:
v1=[0;3]

2-element Vector{Int64}:
 0
 3

In [8]:
inv(M1)*v1*9

2-element Vector{Float64}:
  3.0
 -2.0

In [9]:
using Symbolics

In [10]:
@variables x y k m;

In [12]:
D=Symbolics.Differential(x)

(::Symbolics.Differential) (generic function with 2 methods)

In [13]:
A=(0.7*k^2)/(m^2*((k^2/m^2)+(pi^2/900)))

(0.7(k^2)) / ((m^2)*(0.010966227112321508 + (k^2) / (m^2)))

In [14]:
B=(0.7*k*pi)/(m*30*((k^2/m^2)+(pi^2/900)))

(2.199114857512855k) / (30m*(0.010966227112321508 + (k^2) / (m^2)))

In [ ]:
y=A*cos((pi/30)*x)+B*sin((pi/30)*x)

In [15]:
sqrt(1000/3)

18.257418583505537

In [17]:
L=0.97*10^(-6)

9.700000000000002e-7

In [23]:
om1=503000*2*pi

3.1604422095113317e6

In [24]:
om2=1629000*2*pi

1.0235308865395546e7

In [25]:
1/(L*om1^2)

1.0321256209982197e-7

In [26]:
1/(L*om2^2)

9.840708341600787e-9

In [41]:
R=263

263

In [42]:
C=1.2*10^(-6)

1.2000000000000004e-6

In [43]:
L=1426.10*10^(-3)

1.4261000000000001

In [44]:
om=122*2*pi

766.5486074759095

In [45]:
S=om*L-1/(om*C) # reactance

6.051040898066276

In [46]:
Z=sqrt(R^2+S^2) # impedance

263.06960123881674

In [47]:
dd=atan(S/R)

0.02300370158451917

In [48]:
tL=dd/om

3.0009449316287634e-5

In [49]:
R=222

222

In [50]:
C=1.6*10^(-6)

1.6000000000000008e-6

In [52]:
L=0.53

0.53

In [53]:
om=174*2*pi

1093.274243449248

In [54]:
S=om*L-(1/(om*C))

7.758110910661458

In [55]:
Z=sqrt(R^2+S^2)

222.1355178374276

In [57]:
atan(S/R)/om

3.195193704160775e-5

In [59]:
1093.27424344925*0.53-1/(1093.27424344925*1.6*10^(-6))

7.758110910663731

In [60]:
sqrt(980/3)

18.07392228230128

In [61]:
log(10.5/12)/60

-0.0022255232104087105

In [62]:
(-27/5)*sin(3*(pi/4)+(7*pi/12))

4.676537180435968

In [63]:
-(4.677*pi/4)-0.9

-4.573307210209865

In [64]:
F(y)=(1/5)*y^5-(4/3)*y^3+4*y

F (generic function with 1 method)

In [65]:
F(sqrt(2))-F(-sqrt(2))

6.0339778661252055

In [79]:
using Polynomials

In [67]:
p1=Polynomial([24,4,1/8])

Polynomial(24.0 + 4.0*x + 0.125*x^2)

In [70]:
Polynomials.roots(p1)

2-element Vector{Float64}:
 -24.0
  -8.0

In [71]:
M1=[1 1
-24 -8]

2×2 Matrix{Int64}:
   1   1
 -24  -8

In [72]:
v1=[0
4]

2-element Vector{Int64}:
 0
 4

In [73]:
inv(M1)*v1

2-element Vector{Float64}:
 -0.24999999999999997
  0.24999999999999994

In [74]:
using Roots

In [75]:
f1(x)=(2/3)*cos(2*x)-(2/3)*cos(x)

f1 (generic function with 1 method)

In [76]:
f1(4*pi/3)

7.771561172376096e-16

In [81]:
p2=Polynomial([1/0.049,4,0.03])

Polynomial(20.408163265306122 + 4.0*x + 0.03*x^2)

In [82]:
Polynomials.roots(p2)

2-element Vector{Float64}:
 -128.01951774631013
   -5.313815587023212

In [83]:
5157.50/2

2578.75